export type AuthenticationErrorCode =
    "ACCESS_TOKEN_INVALID" |
    "ACCESS_TOKEN_MALFORMED" |
    "ACCESS_TOKEN_EXPIRED" |
    "ACCESS_TOKEN_NOT_EXPIRED" |
    "ACCESS_TOKEN_NOT_FOUND" |

    "REFRESH_TOKEN_INVALID" |
    "REFRESH_TOKEN_EXPIRED" |

    "COOKIES_NOT_FOUND" |

    "USER_NOT_FOUND" |
    "USER_ALREADY_EXISTS";